### ISSUE TITLE
llvm-flang is failing to build

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/clang-builder#27]
https://github.com/compiler-explorer/infra/runs/4069281414?check_suite_focus=true (click to open the build step)

@Sameeranjoshi - do you know who to talk to about this?

**Comment by mattgodbolt** [comment]
Error is:
```
  CMake Error at CMakeLists.txt:97 (message):
    Clang is not enabled, but is required for the Flang driver
  
  
  -- Configuring incomplete, errors occurred!
```

So I guess maybe we just need to add clang to the list...

**Comment by mattgodbolt** [comment]
I added it to the list and we'll see...

**Comment by Sameeranjoshi** [comment]
Ya, please add clang to the list of builds as flang driver depends on clang
driver.

For recent developments I think Andrzej warzynski(
***@***.***) from arm may be the best person to ask if some
new changes are in driver part.

Other than that pinging the mailing list(flang-dev) would be the best
option for letting people know about the godbolt flang compiler.

I am not working on the project so I am not updated with current status.

Thanks

**Comment by mattgodbolt** [comment]
Thanks @Sameeranjoshi . The email address you mentioned got blanked for privacy reasons by github, but I can ask around.

In other news, llvm-flang now fails to build as it seems to kill the (new) runner:

```
The self-hosted runner: i-0752cedb3b50eb50c lost communication with the server. Verify the machine is running and has a healthy network connection. Anything in your workflow that terminates the runner process, starves it for CPU/Memory, or blocks its network access can cause this error.
```

It only seems to be the llvm-flang build that kills us, though that could be an issue on our side.

**Comment by Sameeranjoshi** [comment]
andrzej [dot] warzynski [at] gmail [dot] com

**Comment by mattgodbolt** [comment]
Thanks @Sameeranjoshi !

**Comment by mattgodbolt** [comment]
So it looks like it's running out of memory. I got a snapshot just before it died.
![Screenshot from 2021-12-06 21-57-46](https://user-images.githubusercontent.com/633973/144963794-17464999-9ca9-46c6-b690-d65f82f5e17b.png)

I'm guessing lots of linkers going on?

**Comment by mattgodbolt** [comment]
See https://github.com/compiler-explorer/clang-builder/commit/4f0ff86ec57c3e0051649beb86bf667b422d0acf

**Comment by mattgodbolt** [comment]
Restricting to 4 links didn't help (assuming I did it right).

**Comment by banach-space** [comment]
Hi @mattgodbolt, hi @Sameeranjoshi 👋🏻 

Thank you for your e-mail! I'm replying here so that more people can participate (in case I missed anything).

Sadly, LLVM Flang has rather extreme memory requirements. From my personal experience, 64GB should be sufficient. From the screenshot that you copied above, it looks like the build is crashing at compile rather than link time. This makes sense and (AFAIK) is due to a heavy use of templates in various parts of LLVM Flang (hence heavy use of memory at compile time).

I wasn't able to dig out the actual build commands that are used here. I've checked the action for building Clang and I saw `ninja install`. This might be too ambitious for LLVM Flang. From [ninja docs](https://ninja-build.org/manual.html#_running_ninja)
> Builds are always run in parallel, based by default on the number of CPUs your system has. 

AFAIK, `ninja` is equivalent to `ninja -j64` (on a 64 core machine). I would start by experimenting with `ninja -j32` (basically, `nproc`/2) and see what happens. You can then try gradually increasing the number of jobs to speed things up. Similar logic applies to `make` (though the default behaviour of `make` and `ninja` is different). I'm not aware of any CMake setting that would help here (e.g. tweaking the number of links jobs is unlikely to help).

thanks for working on this and for Compiler Explorer!
-Andrzej

**Comment by mattgodbolt** [comment]
Thanks @banach-space -- I will try limiting the parallel using clang's own throttling - https://llvm.org/docs/CMake.html#frequently-used-llvm-related-variables suggests I can also reduce the number of compilations as well as link steps (when using `ninja`, specifically, which as you potin out we do)

Thanks!

**Comment by kiranchandramohan** [comment]
Can you also use gold or lld to link? -DLLVM_USE_LINKER=gold 
Sometimes the compilation of files and link steps overlap.

**Comment by mattgodbolt** [comment]
Thanks -- we can definitely give that a go. I am pretty sure we have `gold` available in our build env.

**Comment by mattgodbolt** [comment]
And we built!

https://github.com/compiler-explorer/compiler-workflows/actions/runs/1554449377

Thanks all!
